#配置视图解释器
#  spring.mvc.view.suffix=.jsp
#  spring.mvc.view.prefix=/WEB-INF/views/
  #tomcat的编码配置
#  server.tomcat.uri-encoding=UTF-8
#  spring.http.encoding.charset=UTF-8
#  spring.http.encoding.enabled=true
#  spring.http.encoding.force=true
#  spring.messages.encoding=UTF-8
#
#  server.port=80
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
server:
  tomcat:
    uri-encoding: utf-8
  port: 80
---
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles: prod
---
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8888
spring:
  profiles: test

mybatis:
  type-aliases-package: cn.ken.entity